"""Template generator for creating team project files.

Extracted from TemplateService (Sprint R1) to follow Single Responsibility Principle.
Handles generation of:
- README.md
- WHITEBOARD.md
- BACKLOG.md
- setup-team.sh
- .claude/commands/init-role.md
"""

from pathlib import Path
from app.models.schemas import TeamTemplate


class TemplateGenerator:
    """Generator for team template files and scripts."""

    def generate_readme(
        self, output_dir: Path, project_name: str, template: TeamTemplate
    ) -> None:
        """Generate README.md for the team."""
        roles_table = "\n".join(
            f"| {r.id} | {r.name} | {r.description} |" for r in template.roles
        )
        content = f"""# {project_name}

**Template**: {template.display_name}
**Created**: Auto-generated by AI Teams Controller

## Roles

| ID | Name | Description |
|----|------|-------------|
{roles_table}

## Quick Start

1. Attach to session: `tmux attach -t {project_name}`
2. Send message to PM: `>>> your message`
3. Watch team work autonomously

## Files

| File | Purpose |
|------|---------|
| WHITEBOARD.md | Current story status |
| BACKLOG.md | Future work items |
| prompts/ | Role prompt files |
"""
        (output_dir / "README.md").write_text(content)

    def generate_whiteboard(self, output_dir: Path, project_name: str) -> None:
        """Generate WHITEBOARD.md for the team."""
        content = f"""# WHITEBOARD - {project_name}

**Purpose**: Real-time workspace for CURRENT story only.

**Last Updated**: (auto)
**Current Story**: None

---

## Team Status

| Role | Status | Current Task |
|------|--------|--------------|
| PM   | READY  | Awaiting directive |

---

## Instructions

Keep WHITEBOARD lean - this is for CURRENT work only.
"""
        (output_dir / "WHITEBOARD.md").write_text(content)

    def generate_backlog(self, output_dir: Path, project_name: str) -> None:
        """Generate BACKLOG.md for the team."""
        content = f"""# BACKLOG - {project_name}

**Purpose**: Future work items that PM will prioritize.

---

## High Priority (P0-P1)

(None yet)

---

## Medium Priority (P2)

(None yet)

---

## Low Priority (P3)

(None yet)
"""
        (output_dir / "BACKLOG.md").write_text(content)

    def generate_setup_script(
        self, team_dir: Path, project_name: str, template: TeamTemplate
    ) -> None:
        """Generate setup-team.sh script.

        Args:
            team_dir: Team directory (~/dev/tmux-teams/{project_name}/docs/tmux/{project_name}/)
            project_name: Name of the project/team
            template: Template with role definitions
        """
        roles = template.roles
        num_roles = len(roles)

        # Generate pane creation commands (horizontal split)
        split_commands = "\n".join(
            f"tmux split-window -h -t $SESSION_NAME" for _ in range(num_roles - 1)
        )

        # Generate pane title commands
        title_commands = "\n".join(
            f'tmux select-pane -t $SESSION_NAME:0.{i} -T "{r.id}"'
            for i, r in enumerate(roles)
        )

        # Generate @role_name commands
        role_name_commands = "\n".join(
            f'tmux set-option -p -t $SESSION_NAME:0.{i} @role_name "{r.id}"'
            for i, r in enumerate(roles)
        )

        # Generate Claude startup commands (fire-and-forget, no waiting)
        claude_start_commands = "\n".join(
            f'tmux send-keys -t $SESSION_NAME:0.{i} "cd $PROJECT_ROOT && claude" C-m'
            for i in range(num_roles)
        )

        # Generate init-role commands with delays
        init_role_commands = "\n".join(
            f'tmux send-keys -t $SESSION_NAME:0.{i} "/init-role {r.id}" C-m && sleep 1 && tmux send-keys -t $SESSION_NAME:0.{i} C-m'
            for i, r in enumerate(roles)
        )

        content = f'''#!/bin/bash
# {project_name} - Team Setup Script
# Generated by AI Teams Controller

set -e

# TEAM_DIR is where this script lives (docs/tmux/{project_name}/)
TEAM_DIR="$(cd "$(dirname "$0")" && pwd)"
# PROJECT_ROOT is 3 levels up from TEAM_DIR
PROJECT_ROOT="$(cd "$TEAM_DIR/../../.." && pwd)"
SESSION_NAME="${{SESSION_NAME:-{project_name}}}"

echo "=== {project_name} Team Setup ==="
echo "Project: $PROJECT_ROOT"
echo "Team Dir: $TEAM_DIR"
echo "Session: $SESSION_NAME"
echo ""

# Kill existing session if exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo "Killing existing session..."
    tmux kill-session -t $SESSION_NAME
fi

# Create new session from project root
cd "$PROJECT_ROOT"
tmux new-session -d -s $SESSION_NAME -x 200 -y 50

# Create {num_roles}-pane layout
{split_commands}
tmux select-layout -t $SESSION_NAME even-horizontal

# Set pane titles
{title_commands}

# Set @role_name options
{role_name_commands}

# Resize window
tmux resize-window -t $SESSION_NAME -x 600 -y 50

# Start Claude Code in each pane (fire-and-forget)
echo "Starting Claude Code in all panes..."
{claude_start_commands}

# Wait for Claude to start accepting input
echo "Waiting for Claude Code to initialize..."
sleep 15

# Send /init-role commands (queued, will execute when Claude is ready)
echo "Sending /init-role commands..."
{init_role_commands}

# Move cursor to first pane
tmux select-pane -t $SESSION_NAME:0.0

echo ""
echo "=== Setup Complete! ==="
echo "Attach: tmux attach -t $SESSION_NAME"
echo ""
echo "Claude Code started in all panes with /init-role queued."
echo "Agents will initialize when Claude Code is ready."
echo ""
'''
        script_path = team_dir / "setup-team.sh"
        script_path.write_text(content)
        # Make executable
        script_path.chmod(0o755)

    def generate_init_role_skill(
        self, project_dir: Path, project_name: str, template: TeamTemplate
    ) -> None:
        """Generate .claude/commands/init-role.md skill for the team."""
        # Create .claude/commands directory at project root
        commands_dir = project_dir / ".claude" / "commands"
        commands_dir.mkdir(parents=True, exist_ok=True)

        # Generate role prompts list (prompts are in docs/tmux/{project_name}/prompts/)
        role_prompts = "\n".join(
            f"- **{role.id}** ({role.name}): `docs/tmux/{project_name}/prompts/{role.id}.md`"
            for role in template.roles
        )

        content = f'''# Initialize Agent Role

You are initializing as a member of the **{project_name}** team.

## Step 1: Read Team Documentation

Read the team overview (all in docs/tmux/{project_name}/ folder):
- **README**: `docs/tmux/{project_name}/README.md`
- **Current Status**: `docs/tmux/{project_name}/WHITEBOARD.md`
- **Backlog**: `docs/tmux/{project_name}/BACKLOG.md`

## Step 2: Read Your Role Prompt

Based on the role argument `$ARGUMENTS`, read your specific role prompt:

{role_prompts}

## Step 3: Understand Your Mission

After reading your role prompt:
1. Confirm your role and responsibilities
2. Check the WHITEBOARD for current status
3. Be ready to execute your role in the workflow

## Step 4: Announce Readiness

After initialization, announce:
```
[ROLE] initialized and ready.
Team: {project_name}
WHITEBOARD status: [status from WHITEBOARD.md]
Awaiting directives.
```
'''
        (commands_dir / "init-role.md").write_text(content)
